title: Cheminformatic Practice
description: A place to practice code
show_downloads: true
google_analytics:
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one