project:
  type: website
  output-dir: docs

website:
  title: 'Test'
  site-url: ''
  description: ''
  favicon: '''
  navbar:
    right:
      - 2023-11-01.md
      - icon: github
        href: https://github.com/tlint101/practice-cheminformatics-blog
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

comments:
  utterances:
    repo: tlint101/practice-cheminformatics-blog

execute:
  freeze: auto