project:
  type: website
  output-dir: docs

website:
  title: "Home"
  site-url: https://tlint101.github.io/practice-in-code/
  description: "Practice in Code"
  page-footer: "Website made with [Quarto](https://quarto.org/) by Tony E. Lin© 2023 - 2024"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tlint101/practice-in-code/
      - icon: rss
        href: index.xml
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

comments:
  utterances:
    repo: https://github.com/tlint101/practice-in-code/tree/main

execute:
  freeze: auto
  