project:
  type: website
  output-dir: docs

website:
  title: "Practice Cheminformatics"
  site-url: https://tlint101.github.io/practice-blog/
  description: "Practice Code"
  favicon:
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tlint101/Cheminformatic-Practice
      - icon: rss
        href: index.xml
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

comments:
  utterances:
    repo: https://github.com/tlint101/practice-blog/tree/main

execute:
  freeze: auto
  